// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahhamodpkwgdgtwwpbom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoaGFtb2Rwa3dnZGd0d3dwYm9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTcwMjYsImV4cCI6MjA3MDU5MzAyNn0.K-jxwwJtIXnpN3qWCqAjowidgpPJMtgPMd3rBBWwqCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});